
/*
 * Copyright Anatoly Starostin (c) 2017.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 20 02:24:17 MSK 2017
//----------------------------------------------------

package treeton.prosody.mdlcompiler;

/** CUP generated interface containing symbol constants. */
public interface MdlSymbols {
  /* terminals */
  public static final int RBRACK = 21;
  public static final int QUESTION = 23;
  public static final int SEMICOLON = 22;
  public static final int PLUS = 24;
  public static final int OR = 26;
  public static final int RBRACE = 19;
  public static final int RPAREN = 17;
  public static final int OBLIGATORY_UNSTRESSED = 8;
  public static final int LBRACK = 20;
  public static final int BOOLEAN_LITERAL = 12;
  public static final int IDENTIFIER = 27;
  public static final int NAME = 5;
  public static final int STRESSED = 7;
  public static final int LBRACE = 18;
  public static final int LPAREN = 16;
  public static final int STRING_LITERAL = 10;
  public static final int PRIORITY = 3;
  public static final int MULT = 25;
  public static final int EOF = 0;
  public static final int UNSTRESSED = 9;
  public static final int error = 1;
  public static final int FLOATING_POINT_LITERAL = 14;
  public static final int INTEGER_LITERAL = 11;
  public static final int CHARACTER_LITERAL = 15;
  public static final int OBLIGATORY_STRESSED = 6;
  public static final int THRESHOLD = 4;
  public static final int METER = 2;
  public static final int NULL_LITERAL = 13;
}

